require 'faker'
require 'date'

Review.destroy_all
Order.destroy_all
DishAvailability.destroy_all
Dish.destroy_all
User.destroy_all

cook_category = ["hobbyist", "professional cook"]

array_user = [
{ first_name: "Gregorio",
  last_name: "Fracassi",
  photo: "https://avatars2.githubusercontent.com/u/44582817?v=4",
  email: "gre.fra@gmail.com",
  password: "123456",
  phone_number: "+39-350-5555-90",
  category: "Amateur",
  bio: "Very good italian Food",
  is_chef: true,
  address: "15 Via Maurizio Quadrio, Milano",
},
{ first_name: "Ali",
  last_name: "Abbas",
  photo: "https://avatars1.githubusercontent.com/u/18402851?v=4",
  email: "ali.a@gmail.com",
  password: "123456",
  phone_number: "+39-313-5555-242",
  category: "Amateur",
  bio: "Make the best hummus ever",
  is_chef: true,
  address: "3 Via Massimo D'Azeglio, Milano",
},
{ first_name: "Adam",
  last_name: "Somora",
  photo: "https://avatars1.githubusercontent.com/u/37966273?v=4",
  email: "adamsomsom@gmail.com",
  password: "123456",
  phone_number: "+39-371-0555-5789",
  category: "Amateur",
  bio: "Expert in sandwich preparation",
  address: "7 Via Tito Speri, Milano",
  is_chef: true,
},
{ first_name: "Aymeric",
  last_name: "Azan",
  photo: "https://avatars0.githubusercontent.com/u/50101174?v=4",
  email: "aymeric@gmail.com",
  password: "123456",
  phone_number: "+39-311-0555-571",
  category: "Amateur",
  bio: "Makes the best fondue from Switzerland",
  is_chef: true,
  address: "2 Via Pietro Maroncelli, Milano",
},
{ first_name: "Francesco",
  last_name: "Ecclesie",
  photo: "https://res.cloudinary.com/wagon/image/upload/c_fill,g_face,h_200,w_200/kjacdhhsb16lj3x3uif0.jpg",
  email: "Fra@gmail.com",
  password: "123456",
  phone_number: "+39-324-5555-896",
  category: "Amateur",
  bio: "Banana all the way!",
  is_chef: true,
  address: "5 Via Privata Nino Bonnet, Milano",
},
{ first_name: "Sebastien",
  last_name: "Saunier",
  photo: "https://res.cloudinary.com/wagon/image/upload/c_fill,g_face,h_200,w_200/lxpghuy9ljoa9mcwrrby.jpg",
  email: "sebastien.s@gmail.com",
  password: "123456",
  phone_number: "+39-313-5554-76",
  category: "Professional",
  bio: "Very good chef from Paris",
  is_chef: true,
  address: "52 Corso Magenta, Milano",
},
{ first_name: "Angelo",
  last_name: "Colardo",
  photo: "https://avatars0.githubusercontent.com/u/47533338?v=4",
  email: "angelo.c@gmail.com",
  password: "123456",
  phone_number: "+39-371-1555-76",
  category: "Amateur",
  bio: "Make the best italian food",
  is_chef: true,
  address: "4 Via Carlo Farini, Milano",
},
{ first_name: "Alexander",
  last_name: "Hill",
  photo: "https://res.cloudinary.com/wagon/image/upload/c_fill,g_face,h_200,w_200/j8jofdljsj0jp1yhehum.jpg",
  email: "alexhill@gmail.com",
  password: "123456",
  phone_number: "+39-350-5555-1160",
  category: "Amateur",
  bio: "Italian food amateur from Manchester",
  is_chef: true,
  address: "1 Viale Pasubio, Milano",
},
{ first_name: "Luigi",
  last_name: "Manganiello",
  photo: "https://res.cloudinary.com/wagon/image/upload/c_fill,g_face,h_200,w_200/jfxxykkc6fxrdbghzjuo.jpg",
  email: "luigi@gmail.com",
  password: "123456",
  phone_number: "+39-380-5552-97",
  category: "Amateur",
  bio: "Looking for good food around home",
  is_chef: false,
  address: "9 Viale Pasubio, Milano",
},
{ first_name: "Arbi",
  last_name: "Velaj",
  photo: "https://avatars2.githubusercontent.com/u/26385065?v=4load/c_fill,g_face,h_200,w_200/jfxxykkc6fxrdbghzjuo.jpg",
  email: "arbi@gmail.com",
  password: "123456",
  phone_number: "+39-311-0055-518",
  category: "Professional",
  bio: "Make the best salads",
  is_chef: true,
  address: "21 Viale Pasubio, Milano",
},
{ first_name: "Pietro",
  last_name: "Ventimiglia",
  photo: "https://avatars1.githubusercontent.com/u/50101372?v=4",
  email: "pietro@gmail.com",
  password: "123456",
  phone_number: "+39-311-0055-518",
  category: "Amateur",
  bio: "Like to discover new dishes",
  is_chef: false,
  address: "2 Via Pietro Maroncelli, Milano",
},
{ first_name: "Alessio",
  last_name: "Bezzi",
  photo: "https://avatars1.githubusercontent.com/u/50101065?v=4",
  email: "bezzi@gmail.com",
  password: "123456",
  phone_number: "+39-330-5553-8272",
  category: "Amateur",
  bio: "Downloaded the app but still think that Fidelis is better",
  is_chef: false,
  address: "11 Via Privata Nino Bonnet, Milano",
}
]

array_user.each do |user|

u = User.new(first_name: user[:first_name],
            last_name: user[:last_name],
            email: user[:email],
            password: user[:password],
            phone_number: user[:phone_number],
            category: user[:category],
            bio: user[:bio],
            is_chef: user[:is_chef],
            address: user[:address],)
u.remote_photo_url = user[:photo]
u.save!

end



#############################################

allergens = ["Cereals containing gluten", "Crustaceans", "Eggs", "Fish", "Peanuts", "Soybeans", "Milk", "Nuts", "Celery", "Mustard", "Sesame seeds", "Sulphur dioxide and sulphites", "Lupin", "Molluscs"]
cuisine = []


array_dish = [
{ title: "Fish and Chips",
  ingredients: "Fish, Chips, Fries",
  photo: "https://www.cuisinefiend.com/RecipeImages/Fish%20and%20chips/fish-and-chips-main.jpg",
  user: User.where(is_chef: true).sample,
  allergens: "None",
  cuisine: "English",
  price: 12,
},
{ title: "Pizza napoletana",
  ingredients: "Tomato, Mozarella, Black Olives, Anchovy",
  photo: "https://dailyhomemade.files.wordpress.com/2011/04/pizza-016.jpg",
  user: User.where(is_chef: true).sample,
  allergens: "Milk",
  cuisine: "Italian",
  price: 11,
},
{ title: "Cesar Salad",
  ingredients: "Chicken, Salad, Bread",
  photo: "https://www.seriouseats.com/recipes/images/2016/04/20131009-caesar-salad-food-lab-11-Edit-1500x1125.jpg",
  user: User.where(is_chef: true).sample,
  allergens: "None",
  cuisine: "European",
  price: 9,
},
{ title: "Poke",
  ingredients: "Salmon, Avocado, Rice, Soya",
  photo: "https://2.bp.blogspot.com/-llReyuFYMRg/XApxJvY2YcI/AAAAAAAAJf0/WAKoYjnIzUEgs7QYJNAuqSvmJgJqP0ZWACKgBGAs/s1600/IMG_0493.JPG",
  user: User.where(is_chef: true).sample,
  allergens: "Soybeans",
  cuisine: "Japan",
  price: 13,
},
{ title: "Beef tartare",
  ingredients: "Beef, Egg, Salt, Ketchup, Onions",
  photo: "https://jesspryles.com/wp-content/uploads/2015/12/steak-tartare-39.jpg",
  user: User.where(is_chef: true).sample,
  allergens: "Eggs",
  cuisine: "European",
  price: 16,
},
{ title: "Spahetti alla Bolognese",
  ingredients: "Spahetti, Beef, Tomato, Onions",
  photo: "https://ichef.bbci.co.uk/food/ic/food_16x9_832/recipes/easy_spaghetti_bolognese_93639_16x9.jpg",
  user: User.where(is_chef: true).sample,
  allergens: "Gluten",
  cuisine: "Italian",
  price: 7,
},
{ title: "Piadina",
  ingredients: "Ham, Cheese, Olive Oil",
  photo: "https://www.dissapore.com/wp-content/uploads/2018/06/piadina-copertina-1300x867.jpg",
  user: User.where(is_chef: true).sample,
  allergens: "None",
  cuisine: "Italian",
  price: 4,
},
{ title: "Quinoa Salad",
  ingredients: "Vegetables, Quinoa",
  photo: "https://i2.wp.com/www.by-rosie.com/wp-content/uploads/2018/01/mung-bean-quinoa-cover.jpg?resize=1170%2C617",
  user: User.where(is_chef: true).sample,
  allergens: "Cereals containing gluten",
  cuisine: "Moroccan",
  price: 9,
},
{ title: "Beef Tagliata",
  ingredients: "Beef, Rosemary, Salt, Salad",
  photo: "http://www.passionandcooking.com/wp-content/uploads/2013/06/tagliata-fette.jpg",
  user: User.where(is_chef: true).sample,
  allergens: "None",
  cuisine: "Italian",
  price: 9,
},
{ title: "Risotto alla Milanese ",
  ingredients: "Rice, Cheese, Safran",
  photo: "https://www.eccolecco.it/wp-content/uploads/risotto-giallo.jpg",
  user: User.where(is_chef: true).sample,
  allergens: "Milk",
  cuisine: "Italian",
  price: 10,
},
{ title: "Miso soup",
  ingredients: "Water, Vegetables",
  photo: "https://food-images.files.bbci.co.uk/food/recipes/springmisosoup_72270_16x9.jpg",
  user: User.where(is_chef: true).sample,
  allergens: "None",
  cuisine: "Japan",
  price: 4,
},
{ title: "Club Sandwich",
  ingredients: "Ham, Eggs, Salad, Tomato",
  photo: "https://ls.imgix.net/recipes/thumbnails/LU8-Club-Sandwich.jpg?w=620&h=310&auto=compress,format&fit=crop",
  user: User.where(is_chef: true).sample,
  allergens: "Eggs",
  cuisine: "European",
  price: 9,
},
{ title: "Sea-bass Ceviche",
  ingredients: "Fish, Avocado, Spices",
  photo: "https://fac.img.pmdstatic.net/fit/http.3A.2F.2Fprd2-bone-image.2Es3-website-eu-west-1.2Eamazonaws.2Ecom.2Ffac.2F2018.2F07.2F30.2F2a8fed96-e8b2-4011-825f-dde99156f7eb.2Ejpeg/748x372/quality/80/crop-from/center/ceviche-de-dorade-avocat-coco.jpeg",
  user: User.where(is_chef: true).sample,
  allergens: "None",
  cuisine: "Peruvian",
  price: 11,
},
{ title: "Chicken Noodles",
  ingredients: "Chicken, Vegetables, Rice Noodles, Eggs",
  photo: "https://supervalu.ie/thumbnail/720x400/var/files/good-food-karma/recipe/48779/egg-noodle-stir-fry-recipe-main.jpg?fill=1",
  user: User.where(is_chef: true).sample,
  allergens: "Eggs",
  cuisine: "Asian",
  price: 7,
},
{ title: "Schnitzel",
  ingredients: "Veal Meat",
  photo: "https://www.dessertfortwo.com/wp-content/uploads/2014/12/Schnitzel-2.jpg",
  user: User.where(is_chef: true).sample,
  allergens: "None",
  cuisine: "German",
  price: 9,
},
{ title: "Avocado Salad",
  ingredients: "Avocado, Cucumber, Tomato, Corn",
  photo: "https://hips.hearstapps.com/hmg-prod/images/avocado-salad-1524672116.png",
  user: User.where(is_chef: true).sample,
  allergens: "None",
  cuisine: "Mediterranean",
  price: 5,
},
{ title: "Boiled Salmon and Spinash",
  ingredients: "Salmon, Spinash, Feta Cheese",
  photo: "https://assets.marthastewart.com/styles/wmax-750/d14/med103553_0308/med103553_0308_salmon_horiz.jpg?itok=DCzhoqZv",
  user: User.where(is_chef: true).sample,
  allergens: "None",
  cuisine: "European",
  price: 14,
},
{ title: "Spaghetti alla vongole",
  ingredients: "Spaghetti, Garlic, Pepper, Clams",
  photo: "https://wips.plug.it/cips/buonissimo.org/cms/2012/04/spaghetti-alle-vongole.jpg?w=712&a=c&h=406",
  user: User.where(is_chef: true).sample,
  allergens: "Crustaceans",
  cuisine: "Italian",
  price: 13,
},
{ title: "Ratatouille",
  ingredients: "Vegetables, Rosemary, Olive Oil",
  photo: "https://i.redd.it/5t93id95pfmy.jpg",
  user: User.where(is_chef: true).sample,
  allergens: "None",
  cuisine: "French",
  price: 12,
},
{ title: "Greek Salad",
  ingredients: "Tomato, Romaine Letuce, Red Onions, Black Olives, Feta Cheese, Cucumber",
  photo: "https://cf-images.us-east-1.prod.boltdns.net/v1/static/1033249144001/234f514d-d649-4cf5-b8fc-1a72f5a8c060/2ccb8e7d-62d6-48db-b464-a7213a8fcebc/1280x720/match/image.jpg",
  user: User.where(is_chef: true).sample,
  allergens: "Milk",
  cuisine: "Greek",
  price: 12,
},
{ title: "Paella",
  ingredients: "Rice, Seafood, Vegetables",
  photo: "https://www.ilclubdellericette.it/wp-content/uploads/2017/04/paella.jpg",
  user: User.where(is_chef: true).sample,
  allergens: "Crustaceans",
  cuisine: "Spanish",
  price: 13,
},
{ title: "Quiche",
  ingredients: "Eggs, Cream, Ham",
  photo: "https://ichef.bbci.co.uk/food/ic/food_16x9_832/recipes/quichelorraine_71987_16x9.jpg",
  user: User.where(is_chef: true).sample,
  allergens: "Eggs",
  cuisine: "French",
  price: 7,
},
{ title: "Avocado Toast",
  ingredients: "Avocado, Bread, Spices, Onions, Salmon",
  photo: "https://www.inspiredtaste.net/wp-content/uploads/2018/08/Avocado-Toast-Recipe-1200.jpg",
  user: User.where(is_chef: true).sample,
  allergens: "Cereals containing gluten, Eggs",
  cuisine: "American",
  price: 6,
}
]

array_dish.each do |dish|

d = Dish.new(title: dish[:title],
            ingredients: dish[:ingredients],
            user_id: dish[:user].id,
            allergens: dish[:allergens],
            price: dish[:price])
d.remote_photo_url = dish[:photo]
d.cuisine << dish[:cuisine]
d.save!

end

#######################################

60.times do
  review = Review.new
  review.stars = rand(1..5)
  review.comment = Faker::Restaurant.review
  review.user = User.all.sample
  review.dish = Dish.all.sample
  review.save!
end

30.times do
  dish_availability = DishAvailability.new
  dish_availability.date = Time.at(rand * (Time.now.to_f - 0.0.to_f))
  dish_availability.portion_available = "#{rand(1..12)} servings"
  dish_availability.dish = Dish.all.sample
  dish_availability.price = rand(25..200)/10.0
  dish_availability.save!
end

40.times do
  order = Order.new
  order.user = User.all.sample
  order.dish_availability = DishAvailability.all.sample
  order.status = ["pending", "archived"][rand(0..1)]
  order.save!
end



